// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MundoFinanceiro.Database.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MundoFinanceiro.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191023214257_CriadoTabelaPapeis")]
    partial class CriadoTabelaPapeis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MundoFinanceiro.Database.Contracts.Persistence.Domains.Papel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(6);

                    b.HasKey("Id")
                        .HasName("pk_papeis");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasName("ix_papeis_nome");

                    b.ToTable("papeis");
                });
#pragma warning restore 612, 618
        }
    }
}
